### ISSUE TITLE
If possible, use a better customer identifier than SEN number

### ISSUE THREAD

**Issue by spraot** [thecatontheflat/atlassian-marketplace-tools#1]
If the customer name is consistent, that would be a better option. However, I could imagine this changing over time. I guess that Atlassian probably has a customer ID internally, but we don't get to see this.

Note: this is a farily superficial issue.

**Comment by thecatontheflat** [comment]
@rachetfoot 

The License Detailed View lists all products under the same SEN number (same customer). As far as I know, Atlassian won't change SEN numbers, so I could totally rely on it.

Otherwise, it's not clear what exactly should be changed

**Comment by spraot** [comment]
The issue is that one customer can have multiple SEN numbers, so the "Top Customers" list is not quite a list of customers, but a list of licenses. Like I said, not a huge issue.

**Comment by thecatontheflat** [comment]
Ah, understood!
Good to know, because that's not how things work in Cloud. 
If you have any ideas how to make this widget more meaningful for you, and if it would satisfy Cloud vendors at the same time — I would like to implement it

**Comment by spraot** [comment]
Well, I'm pretty sure it's because some companies run multiple instances of Confluence, so it could happen in the cloud as well. Maybe it's not so common though.

**Comment by nmuldoon** [comment]
Just a thought on this: I want the ability to cross-sell one product to an existing customer. Having some way to aggregate customers (and include all of their SENs) would be really valuable for targeting audiences and creating one-off campaigns.

That functionality is a bit beyond me at present as I'm just getting started. Hopefully that is a good use-case to explain how one customer ID for all SENs could be valuable though.

Do we get anything like that from Marketplace API 2.0?

Thanks,
Nick

**Comment by spraot** [comment]
As far as I could tell from browsing the REST API, 2.0 doesn't add anything to the sales output. So I think we may have to rely on customer name or something like that.

**Comment by thecatontheflat** [comment]
@ratchetfoot @nmuldoon could you may be give me an anonymized example of how license report looks like in the server edition? vitaliy.zurian@agile-values.com

**Comment by thecatontheflat** [comment]
Entities were refactored, this issue is obsolete
