### ISSUE TITLE
Possiblity to populate database without triggering any actions/emails

### ISSUE THREAD

**Issue by spraot** [thecatontheflat/atlassian-marketplace-tools#13]
One way of doing this could be adding a --noaction argument when calling import:sale and import:license. This would not send new sale emails or start mailing campaigns.

**Comment by thecatontheflat** [comment]
It is currently configured via this parameter:
https://github.com/thecatontheflat/atlassian-vendor-tools/blob/master/app/config/parameters.yml.dist#L26

Here is the check:
https://github.com/thecatontheflat/atlassian-vendor-tools/blob/master/src/AppBundle/Command/ImportSaleCommand.php#L91-L93

I assume that switching parameters is not convenient and you'd like to have a flag to override this parameter?

**Comment by spraot** [comment]
Well, there's three places that actions can be triggered: new sales, adding contacts to mailchimp lists, or starting one of the built-in email campaigns. It would be much handier to have a command line switch than to disable and reenable (potentially) all three.

**Comment by thecatontheflat** [comment]
Added a flag for importing sales:
`app/console app:import:sale --new-sale-notification`

By default it will not send any notifications

I'll update the docs during the weekend

**Comment by thecatontheflat** [comment]
https://github.com/thecatontheflat/atlassian-vendor-tools/blob/master/src/AppBundle/Command/ImportSaleCommand.php#L101-L103
