### ISSUE TITLE
Unable to create a new event

### ISSUE THREAD

**Issue by nmuldoon** [thecatontheflat/atlassian-marketplace-tools#14]
Hi Vitaliy,

I started from scratch (git pull, create database & schema, setup parameters, start app) and now experience the following error upon creating an event:

![screen shot 2015-11-09 at 2 40 45 pm](https://cloud.githubusercontent.com/assets/559227/11025519/1777f338-86f0-11e5-8ab5-664ad2c023e4.png)

Suggestions?

Thanks,
Nick

**Comment by thecatontheflat** [comment]
Thank you @nmuldoon 
It is fixed now
