### ISSUE TITLE
Error creating schema

### ISSUE THREAD

**Issue by nmuldoon** [thecatontheflat/atlassian-marketplace-tools#29]
Hello

I get the following error when creating the database:
ATTENTION: This operation should not be executed in a production environment.

Creating database schema...

  [Doctrine\ORM\Tools\ToolsException]  
  Schema-Tool failed with Error 'An exception occurred while executing 'CREATE UNIQUE INDEX license ON license (license_id, addon_key)':  
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "license" already exists' while executing DDL: CREATE UNIQUE INDEX license ON license (license_id,  
   addon_key)                                                                                                                                              

  [Doctrine\DBAL\DBALException]  
  An exception occurred while executing 'CREATE UNIQUE INDEX license ON license (license_id, addon_key)':  
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "license" already exists                            

  [PDOException]  
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "license" already exists  

doctrine:schema:create [--dump-sql] [--em[="..."]]

Here is the sql:

$ app/console doctrine:schema:create --dump-sql
CREATE TABLE drill_registered_event (id INT NOT NULL, drill_schema_event_id INT DEFAULT NULL, drill_registered_schema_id INT DEFAULT NULL, send_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_B114E06C4ACA72F ON drill_registered_event (drill_schema_event_id);
CREATE INDEX IDX_B114E062DDB3692 ON drill_registered_event (drill_registered_schema_id);
CREATE TABLE drill_registered_schema (id INT NOT NULL, license_id VARCHAR(255) NOT NULL, addon_key VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE UNIQUE INDEX per_license ON drill_registered_schema (license_id, addon_key);
CREATE TABLE drill_schema_event (id INT NOT NULL, name VARCHAR(255) NOT NULL, date_shift VARCHAR(255) NOT NULL, date_field VARCHAR(255) NOT NULL, license_type_condition VARCHAR(255) NOT NULL, addon_key VARCHAR(255) NOT NULL, email_template TEXT NOT NULL, email_subject VARCHAR(255) NOT NULL, email_from_email VARCHAR(255) NOT NULL, email_from_name VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE TABLE license (id INT NOT NULL, license_id VARCHAR(255) NOT NULL, organisation_name VARCHAR(255) DEFAULT NULL, addon_name VARCHAR(255) NOT NULL, addon_key VARCHAR(255) NOT NULL, tech_contact_name VARCHAR(255) DEFAULT NULL, tech_contact_email VARCHAR(255) DEFAULT NULL, tech_contact_phone VARCHAR(255) DEFAULT NULL, tech_contact_address_1 VARCHAR(255) DEFAULT NULL, tech_contact_address_2 VARCHAR(255) DEFAULT NULL, tech_contact_city VARCHAR(255) DEFAULT NULL, tech_contact_state VARCHAR(255) DEFAULT NULL, tech_contact_postcode VARCHAR(255) DEFAULT NULL, tech_contact_country VARCHAR(255) DEFAULT NULL, billing_contact_name VARCHAR(255) DEFAULT NULL, billing_contact_email VARCHAR(255) DEFAULT NULL, billing_contact_phone VARCHAR(255) DEFAULT NULL, edition VARCHAR(255) DEFAULT NULL, license_type VARCHAR(255) DEFAULT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, renewal_action VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id));
CREATE UNIQUE INDEX license ON license (license_id, addon_key);
CREATE TABLE sale (id INT NOT NULL, license_type VARCHAR(255) NOT NULL, sale_type VARCHAR(255) NOT NULL, license_id VARCHAR(255) NOT NULL, license_size VARCHAR(255) NOT NULL, country VARCHAR(255) NOT NULL, vendor_amount NUMERIC(6, 2) NOT NULL, plugin_key VARCHAR(255) NOT NULL, invoice VARCHAR(255) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, plugin_name VARCHAR(255) NOT NULL, maintenance_end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, maintenance_start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organisation_name VARCHAR(255) NOT NULL, discounted BOOLEAN NOT NULL, purchase_price NUMERIC(6, 2) NOT NULL, PRIMARY KEY(id));
CREATE UNIQUE INDEX sale ON sale (invoice, license_id, plugin_key);
CREATE SEQUENCE drill_registered_event_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE drill_registered_schema_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE drill_schema_event_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE license_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE sale_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
ALTER TABLE drill_registered_event ADD CONSTRAINT FK_B114E06C4ACA72F FOREIGN KEY (drill_schema_event_id) REFERENCES drill_schema_event (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE drill_registered_event ADD CONSTRAINT FK_B114E062DDB3692 FOREIGN KEY (drill_registered_schema_id) REFERENCES drill_registered_schema (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

Can anyone shed light on why this may be the case?

Thanks,
Nick

**Comment by nmuldoon** [comment]
Also, I get this when running 

$ app/console doctrine:schema:validate
[Mapping]  OK - The mapping files are correct.
[Database] FAIL - The database schema is not in sync with the current mapping file.

**Comment by thecatontheflat** [comment]
@nmuldoon Could you try to execute `app/console doctrine:schema:update --force` ?
