### ISSUE TITLE
Improve "Started Today" list

### ISSUE THREAD

**Issue by spraot** [thecatontheflat/atlassian-marketplace-tools#31]
Since it seems that many new licenses show up with a delay, the "started today" list is often empty, and will never show licenses that show up late in the day (e.g. if the user checks the list once every day at noon, all licenses that show up between noon and midnight will never be shown in the started today list). I suggest showing licenses from today and the previous day. 

An even better solution would be to save the time that each license has most recently been updated and show all licenses that have been updated within the last 24 hours.

**Comment by thecatontheflat** [comment]
Hey @rachetfoot 

Yeah, good point. I was thinking about the same myself recently.
I think, showing just recent licenses (as a widget) would be enough.

I am not sure it would be easy to show the update date of the license, since the date is not stored

**Comment by thecatontheflat** [comment]
I've replaced it with the list of 10 recent licenses
