### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by zhil** [thecatontheflat/atlassian-marketplace-tools#36]
@thecatontheflat it would be nice to add some custom favicon

you could find a lot of free icons here http://www.flaticon.com/search?word=tools&license=all&color=0&stroke=0

**Comment by thecatontheflat** [comment]
Thanks! What do you think about this one?

![diagram](https://cloud.githubusercontent.com/assets/727581/25062235/d5b90a3e-21c8-11e7-8ae0-c3be09ff6cef.png)

**Comment by zhil** [comment]
looks nice, added PR for it

**Comment by thecatontheflat** [comment]
Thanks!
