### ISSUE TITLE
What is Drill schema on the create event page for?

### ISSUE THREAD

**Issue by nmuldoon** [thecatontheflat/atlassian-marketplace-tools#7]
Hi, quick query, what is this field on create event for? 

<img width="282" alt="screen shot 2015-11-05 at 4 55 32 pm" src="https://cloud.githubusercontent.com/assets/559227/10961004/15d00e72-83de-11e5-90c0-b85b6b0f8ab9.png">

Always empty, and I'm getting an error when I try to create an event:

<img width="985" alt="screen shot 2015-11-05 at 4 56 57 pm" src="https://cloud.githubusercontent.com/assets/559227/10961025/41abf88a-83de-11e5-9337-d840092e69cb.png">

**Comment by nmuldoon** [comment]
Googling leads me here: http://stackoverflow.com/questions/21376701/impossible-to-access-an-attribute-username-on-a-null-variable

Unfortunately my PHP is non-existent. I'm guessing that it's because I don't have a Drill schema selected, still unsure what that is used for though.

Thanks

**Comment by thecatontheflat** [comment]
Hi Nick!

Drill schemas are needed to generate emails and sent events.
Here is an example of my configuration in the database. You could try to create something similar:
<img width="441" alt="screen shot 2015-11-05 at 07 38 38" src="https://cloud.githubusercontent.com/assets/727581/10961564/5512df54-8390-11e5-8e17-2dbb91dcce64.png">

Then this dropbox will be populated with data

Or wait until I create a UI for this part

**Comment by nmuldoon** [comment]
Cool, I get it. Would it be possible to populate the drill_schema from the Marketplace API?

Perhaps in that scenario it would automatically pick up new add-ons from a vendor as they are added.

**Comment by thecatontheflat** [comment]
Hm, that's a good idea, totally makes sense :)

I will check such possibility during this weekend

**Comment by thecatontheflat** [comment]
I was thinking about it and it seems that this is a technical leftover from my initial plans: it ought to be possible to have multiple mailing strategies per add-on. But then I found it redundant, since 1 schema per add-on is enough. I'll simplify the relations and remove this "drill_schema" completely

**Comment by thecatontheflat** [comment]
@nmuldoon 
I've removed this redundant table https://github.com/thecatontheflat/atlassian-vendor-tools/pull/12
It is now possible to create an event for any existing addon key
